import { randomUUID } from "node:crypto";
import { DEFAULT_AGENT_ID, DEFAULT_MODEL, fieldId, statusName, webhookIfExpression } from "../marketing-pipeline/logic.js";
import type { FieldMapping } from "../types/field-mapping.js";
import type { N8nNode, N8nWorkflowExport } from "./build-call-agent.js";

const CLICKUP_CREDENTIALS = {
  clickUpApi: { id: "CLICKUP_CREDENTIAL_ID", name: "ClickUp Marketing Pipeline" },
};

function extractWebhookContextJs(): string {
  return [
    "const raw = $input.first().json;",
    "const payload = (raw.body && raw.body.history_items) ? raw.body : raw;",
    "const items = payload.history_items || [];",
    "const first = items[0] || {};",
    "return [{",
    "  json: {",
    "    task_id: String(payload.task_id ?? ''),",
    "    webhook_id: String(payload.webhook_id ?? ''),",
    "    history_item_id: String(first.id ?? ''),",
    "    list_id: String(first.parent_id ?? ''),",
    "    received_at_ms: Date.now(),",
    "  },",
    "}];",
  ].join("\n");
}

function extractTaskFieldsJs(fieldMapping: FieldMapping): string {
  const criteriosId = fieldId(fieldMapping, "criterios_de_aceite");
  const agentFieldId = fieldId(fieldMapping, "agent_id");
  const defaultAgentId = String(fieldMapping.custom_fields.agent_id?.default ?? DEFAULT_AGENT_ID);
  return [
    "const FIELD_IDS = {",
    `  criterios_de_aceite: ${JSON.stringify(criteriosId)},`,
    `  agent_id: ${JSON.stringify(agentFieldId)},`,
    `  default_agent_id: ${JSON.stringify(defaultAgentId)},`,
    "};",
    "",
    "function readCustomField(task, fieldId) {",
    "  if (!fieldId || fieldId === '<TBD>') return '';",
    "  const fields = task.custom_fields || [];",
    "  const match = fields.find((field) => String(field.id) === String(fieldId));",
    "  if (!match || match.value === null || match.value === undefined) return '';",
    "  if (typeof match.value === 'object') {",
    "    return String(match.value.value ?? match.value.name ?? match.value.label ?? '');",
    "  }",
    "  return String(match.value);",
    "}",
    "",
    "const task = $input.first().json;",
    "const webhook = $('Extract Webhook Context').first().json;",
    "const agentId = readCustomField(task, FIELD_IDS.agent_id).trim() || FIELD_IDS.default_agent_id;",
    "",
    "return [{",
    "  json: {",
    "    task_id: String(task.id ?? webhook.task_id ?? ''),",
    "    agent_id: agentId,",
    "    task_title: String(task.name ?? ''),",
    "    task_description: String(task.description ?? task.text_content ?? ''),",
    "    criterios_de_aceite: readCustomField(task, FIELD_IDS.criterios_de_aceite),",
    `    model: ${JSON.stringify(DEFAULT_MODEL)},`,
    "  },",
    "}];",
  ].join("\n");
}

function prepareCallAgentInputJs(): string {
  return [
    "const fields = $('Extract Task Fields').first().json;",
    "return [{",
    "  json: {",
    "    agent_id: fields.agent_id,",
    "    task_title: fields.task_title,",
    "    task_description: fields.task_description,",
    "    criterios_de_aceite: fields.criterios_de_aceite,",
    "    task_id: fields.task_id,",
    "  },",
    "}];",
  ].join("\n");
}

function formatDraftCommentJs(): string {
  return [
    "const agentOutput = $('Execute Call Agent').first().json;",
    "const taskFields = $('Extract Task Fields').first().json;",
    `const agentId = taskFields.agent_id ?? ${JSON.stringify(DEFAULT_AGENT_ID)};`,
    `const model = taskFields.model ?? ${JSON.stringify(DEFAULT_MODEL)};`,
    "",
    "const commentText = [",
    "  '## LinkedIn Draft',",
    "  '',",
    "  agentOutput.deliverable_markdown ?? '',",
    "  '',",
    "  '---',",
    "  '',",
    "  '## Resumo',",
    "  '',",
    "  agentOutput.resumo ?? '',",
    "  '',",
    "  '---',",
    "  '',",
    "  '## Autochecagem',",
    "  '',",
    "  agentOutput.autochecagem ?? '',",
    "  '',",
    "  '---',",
    "  `_Generated by ${agentId} (${model})_`,",
    "].join('\\n');",
    "",
    "return [{",
    "  json: {",
    "    task_id: taskFields.task_id,",
    "    agent_id: agentId,",
    "    model,",
    "    comment_text: commentText,",
    "    deliverable_markdown: agentOutput.deliverable_markdown,",
    "    resumo: agentOutput.resumo,",
    "    autochecagem: agentOutput.autochecagem,",
    "  },",
    "}];",
  ].join("\n");
}

function agentParseFailureJs(): string {
  return [
    "const output = $input.first().json;",
    "const taskFields = $('Extract Task Fields').first().json;",
    "console.log(JSON.stringify({",
    "  task_id: taskFields.task_id,",
    "  agent_id: taskFields.agent_id,",
    "  execution_id: $execution.id,",
    "  parse_success: false,",
    "  error: output.error ?? 'Agent returned error envelope',",
    "}));",
    "throw new Error(`Call Agent failed: ${output.error ?? 'unknown error'}`);",
  ].join("\n");
}

function logIngressSkippedJs(_fieldMapping: FieldMapping): string {
  return [
    "const raw = $input.first().json;",
    "const payload = (raw.body && raw.body.history_items) ? raw.body : raw;",
    "const items = payload.history_items || [];",
    "const first = items[0] || {};",
    "",
    "function statusValue(value) {",
    "  if (value !== null && typeof value === 'object') return String(value.status ?? '').trim().toLowerCase();",
    "  return String(value ?? '').trim().toLowerCase();",
    "}",
    "",
    "const before = statusValue(first.before);",
    "const after = statusValue(first.after);",
    "const transition = before || after ? `${before}->${after}` : '';",
    "",
    "let reason = 'not_entering_ready';",
    "if (!items.length) reason = 'no_history_items';",
    "else if (first.field !== 'status') reason = 'field_not_status';",
    "",
    "const record = {",
    "  event: 'ingress_skipped',",
    "  task_id: String(payload.task_id ?? ''),",
    "  webhook_id: String(payload.webhook_id ?? ''),",
    "  history_item_id: String(first.id ?? ''),",
    "  transition,",
    "  reason,",
    "};",
    "console.log(JSON.stringify(record));",
    "return [{ json: record }];",
  ].join("\n");
}

function dedupIfExpression(): string {
  return (
    `={{ (() => { ` +
    `const staticData = $getWorkflowStaticData('global'); ` +
    `const key = String($json.history_item_id ?? ''); ` +
    `if (!key) return false; ` +
    `staticData.seenHistoryItems = staticData.seenHistoryItems || {}; ` +
    `return Boolean(staticData.seenHistoryItems[key]); ` +
    `})() }}`
  );
}

function markHistoryItemSeenJs(): string {
  return [
    "const staticData = $getWorkflowStaticData('global');",
    "staticData.seenHistoryItems = staticData.seenHistoryItems || {};",
    "const key = String($json.history_item_id ?? '');",
    "if (key) staticData.seenHistoryItems[key] = Date.now();",
    "return [{ json: $json }];",
  ].join("\n");
}

function logDuplicateIngressJs(): string {
  return [
    "const context = $input.first().json;",
    "const record = {",
    "  event: 'ingress_skipped',",
    "  task_id: context.task_id,",
    "  webhook_id: context.webhook_id,",
    "  history_item_id: context.history_item_id,",
    "  transition: '',",
    "  reason: 'duplicate_history_item',",
    "};",
    "console.log(JSON.stringify(record));",
    "return [{ json: record }];",
  ].join("\n");
}

/** Build the Marketing Pipeline n8n main workflow export. Source of truth per ADR-006. */
export function buildMarketingPipelineWorkflow(fieldMapping: FieldMapping): N8nWorkflowExport {
  const statusWriting = statusName(fieldMapping, "writing");
  const statusReview = statusName(fieldMapping, "review");

  const nodes: N8nNode[] = [
    {
      id: randomUUID(),
      name: "ClickUp Webhook",
      type: "n8n-nodes-base.webhook",
      typeVersion: 2,
      position: [0, 300],
      webhookId: randomUUID(),
      parameters: {
        httpMethod: "POST",
        path: "marketing-pipeline-ready-to-work",
        responseMode: "onReceived",
        options: {},
      },
    },
    {
      id: randomUUID(),
      name: "Ready to Work?",
      type: "n8n-nodes-base.if",
      typeVersion: 2.2,
      position: [240, 300],
      parameters: {
        conditions: {
          options: { version: 2, leftValue: "", caseSensitive: true, typeValidation: "loose" },
          combinator: "and",
          conditions: [
            {
              id: randomUUID(),
              leftValue: webhookIfExpression(fieldMapping),
              rightValue: "",
              operator: { type: "boolean", operation: "true", singleValue: true },
            },
          ],
        },
        options: {},
      },
    },
    {
      id: randomUUID(),
      name: "Extract Webhook Context",
      type: "n8n-nodes-base.code",
      typeVersion: 2,
      position: [480, 300],
      parameters: { jsCode: extractWebhookContextJs() },
    },
    {
      id: randomUUID(),
      name: "Dedup?",
      type: "n8n-nodes-base.if",
      typeVersion: 2.2,
      position: [600, 300],
      parameters: {
        conditions: {
          options: { version: 2, leftValue: "", caseSensitive: true, typeValidation: "loose" },
          combinator: "and",
          conditions: [
            {
              id: randomUUID(),
              leftValue: dedupIfExpression(),
              rightValue: "",
              operator: { type: "boolean", operation: "true", singleValue: true },
            },
          ],
        },
        options: {},
      },
    },
    {
      id: randomUUID(),
      name: "Mark History Item Seen",
      type: "n8n-nodes-base.code",
      typeVersion: 2,
      position: [720, 300],
      parameters: { jsCode: markHistoryItemSeenJs() },
    },
    {
      id: randomUUID(),
      name: "GET ClickUp Task",
      type: "n8n-nodes-base.clickUp",
      typeVersion: 1,
      position: [840, 300],
      credentials: CLICKUP_CREDENTIALS,
      parameters: { operation: "get", id: "={{ $json.task_id }}" },
    },
    {
      id: randomUUID(),
      name: "Extract Task Fields",
      type: "n8n-nodes-base.code",
      typeVersion: 2,
      position: [1080, 300],
      parameters: { jsCode: extractTaskFieldsJs(fieldMapping) },
    },
    {
      id: randomUUID(),
      name: "Status → In Progress",
      type: "n8n-nodes-base.clickUp",
      typeVersion: 1,
      position: [1320, 300],
      credentials: CLICKUP_CREDENTIALS,
      parameters: { operation: "update", id: "={{ $json.task_id }}", updateFields: { status: statusWriting } },
    },
    {
      id: randomUUID(),
      name: "Prepare Call Agent Input",
      type: "n8n-nodes-base.code",
      typeVersion: 2,
      position: [1440, 300],
      parameters: { jsCode: prepareCallAgentInputJs() },
    },
    {
      id: randomUUID(),
      name: "Execute Call Agent",
      type: "n8n-nodes-base.executeWorkflow",
      typeVersion: 1.2,
      position: [1680, 300],
      parameters: {
        source: "database",
        workflowId: { __rl: true, mode: "id", value: "CALL_AGENT_WORKFLOW_ID" },
        mode: "once",
        options: {},
      },
    },
    {
      id: randomUUID(),
      name: "Agent Output OK?",
      type: "n8n-nodes-base.if",
      typeVersion: 2.2,
      position: [1920, 300],
      parameters: {
        conditions: {
          options: { version: 2, leftValue: "", caseSensitive: true, typeValidation: "strict" },
          combinator: "and",
          conditions: [
            {
              id: randomUUID(),
              leftValue: "={{ $json.error }}",
              rightValue: "",
              operator: { type: "string", operation: "notExists" },
            },
          ],
        },
        options: {},
      },
    },
    {
      id: randomUUID(),
      name: "Format Draft Comment",
      type: "n8n-nodes-base.code",
      typeVersion: 2,
      position: [2160, 220],
      parameters: { jsCode: formatDraftCommentJs() },
    },
    {
      id: randomUUID(),
      name: "POST Task Comment",
      type: "n8n-nodes-base.clickUp",
      typeVersion: 1,
      position: [2400, 220],
      retryOnFail: true,
      maxTries: 2,
      waitBetweenTries: 1000,
      credentials: CLICKUP_CREDENTIALS,
      parameters: {
        resource: "comment",
        operation: "create",
        commentOn: "task",
        id: "={{ $json.task_id }}",
        commentText: "={{ $json.comment_text }}",
      },
    },
    {
      id: randomUUID(),
      name: "Status → Review",
      type: "n8n-nodes-base.clickUp",
      typeVersion: 1,
      position: [2640, 220],
      credentials: CLICKUP_CREDENTIALS,
      parameters: {
        operation: "update",
        id: "={{ $('Extract Task Fields').item.json.task_id }}",
        updateFields: { status: statusReview },
      },
    },
    {
      id: randomUUID(),
      name: "Agent Parse Failure",
      type: "n8n-nodes-base.code",
      typeVersion: 2,
      position: [2160, 420],
      parameters: { jsCode: agentParseFailureJs() },
    },
    {
      id: randomUUID(),
      name: "Log Ingress Skipped",
      type: "n8n-nodes-base.code",
      typeVersion: 2,
      position: [480, 500],
      parameters: { jsCode: logIngressSkippedJs(fieldMapping) },
    },
    {
      id: randomUUID(),
      name: "Log Duplicate Ingress",
      type: "n8n-nodes-base.code",
      typeVersion: 2,
      position: [600, 500],
      parameters: { jsCode: logDuplicateIngressJs() },
    },
  ];

  const connections: N8nWorkflowExport["connections"] = {
    "ClickUp Webhook": { main: [[{ node: "Ready to Work?", type: "main", index: 0 }]] },
    "Ready to Work?": {
      main: [
        [{ node: "Extract Webhook Context", type: "main", index: 0 }],
        [{ node: "Log Ingress Skipped", type: "main", index: 0 }],
      ],
    },
    "Extract Webhook Context": { main: [[{ node: "Dedup?", type: "main", index: 0 }]] },
    "Dedup?": {
      main: [
        [{ node: "Log Duplicate Ingress", type: "main", index: 0 }],
        [{ node: "Mark History Item Seen", type: "main", index: 0 }],
      ],
    },
    "Mark History Item Seen": { main: [[{ node: "GET ClickUp Task", type: "main", index: 0 }]] },
    "GET ClickUp Task": { main: [[{ node: "Extract Task Fields", type: "main", index: 0 }]] },
    "Extract Task Fields": { main: [[{ node: "Status → In Progress", type: "main", index: 0 }]] },
    "Status → In Progress": { main: [[{ node: "Prepare Call Agent Input", type: "main", index: 0 }]] },
    "Prepare Call Agent Input": { main: [[{ node: "Execute Call Agent", type: "main", index: 0 }]] },
    "Execute Call Agent": { main: [[{ node: "Agent Output OK?", type: "main", index: 0 }]] },
    "Agent Output OK?": {
      main: [
        [{ node: "Format Draft Comment", type: "main", index: 0 }],
        [{ node: "Agent Parse Failure", type: "main", index: 0 }],
      ],
    },
    "Format Draft Comment": { main: [[{ node: "POST Task Comment", type: "main", index: 0 }]] },
    "POST Task Comment": { main: [[{ node: "Status → Review", type: "main", index: 0 }]] },
  };

  return {
    name: "Marketing Pipeline",
    nodes,
    connections,
    active: false,
    settings: { executionOrder: "v1" },
    versionId: randomUUID(),
    meta: { templateCredsSetupCompleted: false, instanceId: "agentic-mkt-marketing-pipeline-export" },
    tags: [{ name: "marketing-pipeline" }],
  };
}
