import {
  DEFAULT_MAX_OUTPUT_TOKENS,
  DEFAULT_MODEL,
  DEFAULT_PROVIDER,
  DEFAULT_TEMPERATURE,
  REQUIRED_OUTPUT_KEYS,
  REQUIRED_STAGE_OUTPUT_KEYS,
} from "../call-agent/logic.js";
import { joinN8nJs } from "./n8n-codegen.js";

export function storeInputContextJs(): string {
  return joinN8nJs([
    "const item = $input.first().json;",
    "return [{",
    "  json: {",
    "    ...item,",
    "    _started_at_ms: Date.now(),",
    "    task_id: item.task_id ?? item.task_title ?? 'isolation-test',",
    "  },",
    "}];",
  ]);
}

export function parseAgentConfigJs(): string {
  return joinN8nJs([
    "const input = $('Store Input Context').first().json;",
    "const github = $input.first().json;",
    "const encoded = github.content;",
    "if (!encoded) {",
    "  return [{ json: { error: 'GitHub agent config fetch failed', raw_response: JSON.stringify(github) } }];",
    "}",
    "const decoded = Buffer.from(String(encoded).replace(/\\n/g, ''), 'base64').toString('utf8');",
    "const agentConfig = JSON.parse(decoded);",
    "const skills = Array.isArray(agentConfig.skills) ? agentConfig.skills : [];",
    "const references = Array.isArray(agentConfig.references) ? agentConfig.references : [];",
    "const items = [",
    "  ...skills.map((skill) => ({",
    "    json: {",
    "      ...input,",
    "      agent_config: agentConfig,",
    "      skill,",
    "      skill_path: `agents/skills/${skill}.md`,",
    "      path: `agents/skills/${skill}.md`,",
    "    },",
    "  })),",
    "  ...references.map((reference) => ({",
    "    json: {",
    "      ...input,",
    "      agent_config: agentConfig,",
    "      reference,",
    "      path: reference,",
    "    },",
    "  })),",
    "];",
    "return items;",
  ]);
}

/** Mirrors `assembleSystemPrompt` + `assembleUserMessage` in call-agent/logic.ts. */
export function assemblePromptJs(): string {
  return joinN8nJs([
    "const items = $input.all();",
    "const base = items[0]?.json ?? {};",
    "const agentConfig = base.agent_config;",
    "if (!agentConfig) {",
    "  return [{ json: { error: 'Missing agent_config after Merge Agent Files Fetch', raw_response: JSON.stringify(base) } }];",
    "}",
    "const skillContents = {};",
    "const referenceContents = {};",
    "for (const item of items) {",
    "  const skill = item.json.skill;",
    "  const reference = item.json.reference;",
    "  const encoded = item.json.content;",
    "  if (!encoded) continue;",
    "  const decoded = Buffer.from(String(encoded).replace(/\\n/g, ''), 'base64').toString('utf8');",
    "  if (skill) {",
    "    skillContents[skill] = decoded;",
    "  } else if (reference) {",
    "    referenceContents[reference] = decoded;",
    "  }",
    "}",
    `const schema = agentConfig.output_schema ?? {};`,
    "const example = {",
    "  deliverable_markdown: schema.deliverable_markdown ?? 'Full LinkedIn post draft in markdown',",
    "  resumo: schema.resumo ?? '2-3 sentence summary of the draft',",
    "  autochecagem: schema.autochecagem ?? 'Bullet list validating draft against acceptance criteria',",
    "};",
    "const skillBlocks = (agentConfig.skills ?? []).map((skill) => {",
    "  const body = (skillContents[skill] ?? '').trim();",
    "  return `## Skill: ${skill}\\n${body}`;",
    "}).join('\\n\\n');",
    "const systemPromptLines = [",
    "  '# Agent Role',",
    "  `You are the \\`${agentConfig.id}\\` marketing worker agent.`,",
    "  '',",
    "  '# Skills',",
    "  skillBlocks,",
    "  '',",
    "];",
    "const references = agentConfig.references ?? [];",
    "if (references.length > 0) {",
    "  const referenceBlocks = references.map((ref) => {",
    "    const body = (referenceContents[ref] ?? '').trim();",
    "    return `## Reference: ${ref}\\n${body}`;",
    "  }).join('\\n\\n');",
    "  systemPromptLines.push('# References', referenceBlocks, '');",
    "}",
    "systemPromptLines.push(",
    "  '# Required Output Format',",
    "  'Respond with JSON only. Do not wrap the JSON in markdown code fences.',",
    "  'Required keys and semantics:',",
    "  JSON.stringify(example, null, 2),",
    ");",
    "const systemPrompt = systemPromptLines.join('\\n');",
    "const userMessage = [",
    "  '# Task Title',",
    "  base.task_title ?? '',",
    "  '',",
    "  '# Task Description',",
    "  base.task_description ?? '',",
    "  '',",
    "  '# Critérios de Aceite',",
    "  base.criterios_de_aceite ?? '',",
    "].join('\\n');",
    "return [{",
    "  json: {",
    "    ...base,",
    "    agent_config: agentConfig,",
    "    skill_contents: skillContents,",
    "    reference_contents: referenceContents,",
    "    system_prompt: systemPrompt,",
    "    user_message: userMessage,",
    `    temperature: agentConfig.temperature ?? ${DEFAULT_TEMPERATURE},`,
    `    max_output_tokens: agentConfig.max_output_tokens ?? ${DEFAULT_MAX_OUTPUT_TOKENS},`,
    `    provider: agentConfig.provider ?? '${DEFAULT_PROVIDER}',`,
    `    model: agentConfig.model ?? '${DEFAULT_MODEL}',`,
    "  },",
    "}];",
  ]);
}

/** Mirrors `stripJsonFences`, `extractOpenAIText`, and `parseAgentOutput` in call-agent/logic.ts. */
export function parseAgentOutputJs(): string {
  return joinN8nJs([
    `const REQUIRED_KEYS = ${JSON.stringify([...REQUIRED_OUTPUT_KEYS])};`,
    "const startedAt = $('Store Input Context').first().json._started_at_ms ?? Date.now();",
    "const input = $('Store Input Context').first().json;",
    "const agentId = input.agent_id ?? 'unknown';",
    "const taskId = input.task_id ?? input.task_title ?? 'unknown';",
    "const executionId = $execution.id;",
    "",
    "function stripFences(text) {",
    "  const trimmed = (text ?? '').trim();",
    "  if (!trimmed.startsWith('```')) return trimmed;",
    "  const lines = trimmed.split('\\n');",
    "  if (lines[0].startsWith('```')) lines.shift();",
    "  if (lines.length && lines[lines.length - 1].trim() === '```') lines.pop();",
    "  return lines.join('\\n').trim();",
    "}",
    "",
    "function extractOpenAIText(item) {",
    "  const json = item.json ?? {};",
    "  const chunks = [];",
    "  const output = json.output;",
    "  if (Array.isArray(output)) {",
    "    for (const message of output) {",
    "      const content = message?.content;",
    "      if (!Array.isArray(content)) continue;",
    "      for (const block of content) {",
    "        if (block?.type !== 'output_text' || block.text == null) continue;",
    "        if (typeof block.text === 'string') chunks.push(block.text);",
    "        else if (typeof block.text === 'object') chunks.push(JSON.stringify(block.text));",
    "      }",
    "    }",
    "  }",
    "  if (chunks.length) return chunks.join('');",
    "  const choice = Array.isArray(json.choices) ? json.choices[0] : null;",
    "  if (choice?.message?.content && typeof choice.message.content === 'string') {",
    "    return choice.message.content;",
    "  }",
    "  for (const key of ['text', 'message']) {",
    "    if (typeof json[key] === 'string') return json[key];",
    "  }",
    "  return JSON.stringify(json);",
    "}",
    "",
    "const rawResponse = extractOpenAIText($input.first());",
    "let parseSuccess = false;",
    "let result;",
    "",
    "try {",
    "  const cleaned = stripFences(rawResponse);",
    "  const parsed = JSON.parse(cleaned);",
    "  if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {",
    "    throw new Error('Expected JSON object');",
    "  }",
    "  const missing = REQUIRED_KEYS.filter((key) => !(key in parsed));",
    "  if (missing.length) throw new Error(`Missing required keys: ${missing.join(', ')}`);",
    "  const invalid = REQUIRED_KEYS.filter((key) => typeof parsed[key] !== 'string' || !parsed[key].trim());",
    "  if (invalid.length) throw new Error(`Empty or non-string values for: ${invalid.join(', ')}`);",
    "  result = {",
    "    deliverable_markdown: parsed.deliverable_markdown,",
    "    resumo: parsed.resumo,",
    "    autochecagem: parsed.autochecagem,",
    "    next_gate: $('Parse Agent Config').first().json.agent_config.output_schema.next_gate",
    "  };",
    "  parseSuccess = true;",
    "} catch (error) {",
    "  result = {",
    "    error: `Failed to parse AgentOutput: ${error.message}`,",
    "    raw_response: rawResponse,",
    "  };",
    "}",
    "",
    "const latencyMs = Date.now() - startedAt;",
    "console.log(JSON.stringify({",
    "  task_id: taskId,",
    "  agent_id: agentId,",
    "  execution_id: executionId,",
    "  latency_ms: latencyMs,",
    "  parse_success: parseSuccess,",
    "}));",
    "",
    "return [{ json: result }];",
  ]);
}

/** Mirrors `parseStageOutput` in call-agent/logic.ts — validates typed stage outputs. */
export function parseStageOutputJs(): string {
  return joinN8nJs([
    `const REQUIRED_STAGE_KEYS = ${JSON.stringify([...REQUIRED_STAGE_OUTPUT_KEYS])};`,
    "const STAGE_DEFINITIONS = {",
    "  investigate: { next_gate: 'brief review' },",
    "  write: { next_gate: 'content review' },",
    "  format: { next_gate: 'final review' },",
    "};",
    "const startedAt = $('Store Input Context').first().json._started_at_ms ?? Date.now();",
    "const input = $('Store Input Context').first().json;",
    "const agentId = input.agent_id ?? 'unknown';",
    "const taskId = input.task_id ?? input.task_title ?? 'unknown';",
    "const executionId = $execution.id;",
    "",
    "function stripFences(text) {",
    "  const trimmed = (text ?? '').trim();",
    "  if (!trimmed.startsWith('```')) return trimmed;",
    "  const lines = trimmed.split('\\n');",
    "  if (lines[0].startsWith('```')) lines.shift();",
    "  if (lines.length && lines[lines.length - 1].trim() === '```') lines.pop();",
    "  return lines.join('\\n').trim();",
    "}",
    "",
    "function extractOpenAIText(item) {",
    "  const json = item.json ?? {};",
    "  const chunks = [];",
    "  const output = json.output;",
    "  if (Array.isArray(output)) {",
    "    for (const message of output) {",
    "      const content = message?.content;",
    "      if (!Array.isArray(content)) continue;",
    "      for (const block of content) {",
    "        if (block?.type !== 'output_text' || block.text == null) continue;",
    "        if (typeof block.text === 'string') chunks.push(block.text);",
    "        else if (typeof block.text === 'object') chunks.push(JSON.stringify(block.text));",
    "      }",
    "    }",
    "  }",
    "  if (chunks.length) return chunks.join('');",
    "  const choice = Array.isArray(json.choices) ? json.choices[0] : null;",
    "  if (choice?.message?.content && typeof choice.message.content === 'string') {",
    "    return choice.message.content;",
    "  }",
    "  for (const key of ['text', 'message']) {",
    "    if (typeof json[key] === 'string') return json[key];",
    "  }",
    "  return JSON.stringify(json);",
    "}",
    "",
    "const rawResponse = extractOpenAIText($input.first());",
    "let parseSuccess = false;",
    "let result;",
    "",
    "try {",
    "  const cleaned = stripFences(rawResponse);",
    "  const parsed = JSON.parse(cleaned);",
    "  if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {",
    "    throw new Error('Expected JSON object');",
    "  }",
    "  const missing = REQUIRED_STAGE_KEYS.filter((key) => !(key in parsed));",
    "  if (missing.length) throw new Error(`Missing required keys: ${missing.join(', ')}`);",
    "",
    "  const stage = parsed.stage;",
    "  if (!stage || !STAGE_DEFINITIONS[stage]) {",
    "    throw new Error(`Unknown stage '${String(stage)}'. Expected one of: investigate, write, format`);",
    "  }",
    "  const stageDefinition = STAGE_DEFINITIONS[stage];",
    "",
    "  const requiredStringFields = ['artifact_markdown', 'resumo', 'self_check'];",
    "  const empty = requiredStringFields.filter((key) => typeof parsed[key] !== 'string' || !parsed[key].trim());",
    "  if (empty.length) throw new Error(`Empty or non-string values for: ${empty.join(', ')}`);",
    "",
    "  const nextGate = parsed.next_gate;",
    "  if (nextGate !== stageDefinition.next_gate) {",
    "    throw new Error(`Invalid next_gate '${String(nextGate)}' for stage '${stage}'. Expected '${stageDefinition.next_gate}'`);",
    "  }",
    "",
    "  if (parsed.blocker_question !== undefined) {",
    "    if (typeof parsed.blocker_question !== 'string' || !parsed.blocker_question.trim()) {",
    "      throw new Error('blocker_question must be a non-empty string when present');",
    "    }",
    "  }",
    "",
    "  result = {",
    "    stage: parsed.stage,",
    "    artifact_markdown: parsed.artifact_markdown,",
    "    resumo: parsed.resumo,",
    "    self_check: parsed.self_check,",
    "    next_gate: parsed.next_gate,",
    "  };",
    "  if (parsed.blocker_question) {",
    "    result.blocker_question = parsed.blocker_question;",
    "  }",
    "  parseSuccess = true;",
    "} catch (error) {",
    "  result = {",
    "    error: `Failed to parse StageAgentOutput: ${error.message}`,",
    "    raw_response: rawResponse,",
    "  };",
    "}",
    "",
    "const latencyMs = Date.now() - startedAt;",
    "console.log(JSON.stringify({",
    "  task_id: taskId,",
    "  agent_id: agentId,",
    "  execution_id: executionId,",
    "  latency_ms: latencyMs,",
    "  parse_success: parseSuccess,",
    "}));",
    "",
    "return [{ json: result }];",
  ]);
}

/** Mirrors `parseCallAgentOutput` in call-agent/logic.ts — dispatches by agent_config.output_schema shape. */
export function parseCallAgentOutputJs(): string {
  return joinN8nJs([
    `const REQUIRED_KEYS = ${JSON.stringify([...REQUIRED_OUTPUT_KEYS])};`,
    `const REQUIRED_STAGE_KEYS = ${JSON.stringify([...REQUIRED_STAGE_OUTPUT_KEYS])};`,
    "const STAGE_DEFINITIONS = {",
    "  investigate: { next_gate: 'brief review' },",
    "  write: { next_gate: 'content review' },",
    "  format: { next_gate: 'final review' },",
    "};",
    "const startedAt = $('Store Input Context').first().json._started_at_ms ?? Date.now();",
    "const input = $('Store Input Context').first().json;",
    "const agentId = input.agent_id ?? 'unknown';",
    "const taskId = input.task_id ?? input.task_title ?? 'unknown';",
    "const executionId = $execution.id;",
    "const agentConfig = $('Assemble Prompt').first().json.agent_config ?? {};",
    "const isStaged = typeof (agentConfig.output_schema ?? {}).stage === 'string';",
    "",
    "function stripFences(text) {",
    "  const trimmed = (text ?? '').trim();",
    "  if (!trimmed.startsWith('```')) return trimmed;",
    "  const lines = trimmed.split('\\n');",
    "  if (lines[0].startsWith('```')) lines.shift();",
    "  if (lines.length && lines[lines.length - 1].trim() === '```') lines.pop();",
    "  return lines.join('\\n').trim();",
    "}",
    "",
    "function extractOpenAIText(item) {",
    "  const json = item.json ?? {};",
    "  const chunks = [];",
    "  const output = json.output;",
    "  if (Array.isArray(output)) {",
    "    for (const message of output) {",
    "      const content = message?.content;",
    "      if (!Array.isArray(content)) continue;",
    "      for (const block of content) {",
    "        if (block?.type !== 'output_text' || block.text == null) continue;",
    "        if (typeof block.text === 'string') chunks.push(block.text);",
    "        else if (typeof block.text === 'object') chunks.push(JSON.stringify(block.text));",
    "      }",
    "    }",
    "  }",
    "  if (chunks.length) return chunks.join('');",
    "  const choice = Array.isArray(json.choices) ? json.choices[0] : null;",
    "  if (choice?.message?.content && typeof choice.message.content === 'string') {",
    "    return choice.message.content;",
    "  }",
    "  for (const key of ['text', 'message']) {",
    "    if (typeof json[key] === 'string') return json[key];",
    "  }",
    "  return JSON.stringify(json);",
    "}",
    "",
    "const rawResponse = extractOpenAIText($input.first());",
    "let parseSuccess = false;",
    "let result;",
    "",
    "try {",
    "  const cleaned = stripFences(rawResponse);",
    "  const parsed = JSON.parse(cleaned);",
    "  if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {",
    "    throw new Error('Expected JSON object');",
    "  }",
    "",
    "  if (isStaged) {",
    "    const missing = REQUIRED_STAGE_KEYS.filter((key) => !(key in parsed));",
    "    if (missing.length) throw new Error(`Missing required keys: ${missing.join(', ')}`);",
    "",
    "    const stage = parsed.stage;",
    "    if (!stage || !STAGE_DEFINITIONS[stage]) {",
    "      throw new Error(`Unknown stage '${String(stage)}'. Expected one of: investigate, write, format`);",
    "    }",
    "    const stageDefinition = STAGE_DEFINITIONS[stage];",
    "",
    "    const requiredStringFields = ['artifact_markdown', 'resumo', 'self_check'];",
    "    const empty = requiredStringFields.filter((key) => typeof parsed[key] !== 'string' || !parsed[key].trim());",
    "    if (empty.length) throw new Error(`Empty or non-string values for: ${empty.join(', ')}`);",
    "",
    "    const nextGate = parsed.next_gate;",
    "    if (nextGate !== stageDefinition.next_gate) {",
    "      throw new Error(`Invalid next_gate '${String(nextGate)}' for stage '${stage}'. Expected '${stageDefinition.next_gate}'`);",
    "    }",
    "",
    "    if (parsed.blocker_question !== undefined) {",
    "      if (typeof parsed.blocker_question !== 'string' || !parsed.blocker_question.trim()) {",
    "        throw new Error('blocker_question must be a non-empty string when present');",
    "      }",
    "    }",
    "",
    "    result = {",
    "      stage: parsed.stage,",
    "      artifact_markdown: parsed.artifact_markdown,",
    "      resumo: parsed.resumo,",
    "      self_check: parsed.self_check,",
    "      next_gate: parsed.next_gate,",
    "    };",
    "    if (parsed.blocker_question) {",
    "      result.blocker_question = parsed.blocker_question;",
    "    }",
    "  } else {",
    "    const missing = REQUIRED_KEYS.filter((key) => !(key in parsed));",
    "    if (missing.length) throw new Error(`Missing required keys: ${missing.join(', ')}`);",
    "    const invalid = REQUIRED_KEYS.filter((key) => typeof parsed[key] !== 'string' || !parsed[key].trim());",
    "    if (invalid.length) throw new Error(`Empty or non-string values for: ${invalid.join(', ')}`);",
    "    result = {",
    "      deliverable_markdown: parsed.deliverable_markdown,",
    "      resumo: parsed.resumo,",
    "      autochecagem: parsed.autochecagem,",
    "    };",
    "  }",
    "  parseSuccess = true;",
    "} catch (error) {",
    "  result = {",
    "    error: `Failed to parse ${isStaged ? 'StageAgentOutput' : 'AgentOutput'}: ${error.message}`,",
    "    raw_response: rawResponse,",
    "  };",
    "}",
    "",
    "const latencyMs = Date.now() - startedAt;",
    "console.log(JSON.stringify({",
    "  task_id: taskId,",
    "  agent_id: agentId,",
    "  execution_id: executionId,",
    "  latency_ms: latencyMs,",
    "  parse_success: parseSuccess,",
    "}));",
    "",
    "return [{ json: result }];",
  ]);
}

export function unsupportedProviderJs(): string {
  return joinN8nJs([
    "return [{",
    "  json: {",
    "    error: `Unsupported provider: ${$json.provider ?? 'unknown'}. M1 routes openai (and legacy google) to GPT.`,",
    "    raw_response: JSON.stringify($json),",
    "  },",
    "}];",
  ]);
}

/** Exported for equivalence tests — mirrors stripJsonFences in logic.ts. */
export const STRIP_JSON_FENCES_JS = [
  "function stripFences(text) {",
  "  const trimmed = (text ?? '').trim();",
  "  if (!trimmed.startsWith('```')) return trimmed;",
  "  const lines = trimmed.split('\\n');",
  "  if (lines[0].startsWith('```')) lines.shift();",
  "  if (lines.length && lines[lines.length - 1].trim() === '```') lines.pop();",
  "  return lines.join('\\n').trim();",
  "}",
  "return stripFences(input);",
].join("\n");

/** Exported for equivalence tests — mirrors extractOpenAIText in logic.ts. */
export const EXTRACT_OPENAI_TEXT_JS = [
  "function extractOpenAIText(json) {",
  "  const chunks = [];",
  "  const output = json.output;",
  "  if (Array.isArray(output)) {",
  "    for (const message of output) {",
  "      const content = message?.content;",
  "      if (!Array.isArray(content)) continue;",
  "      for (const block of content) {",
  "        if (block?.type !== 'output_text' || block.text == null) continue;",
  "        if (typeof block.text === 'string') chunks.push(block.text);",
  "        else if (typeof block.text === 'object') chunks.push(JSON.stringify(block.text));",
  "      }",
  "    }",
  "  }",
  "  if (chunks.length) return chunks.join('');",
  "  const choice = Array.isArray(json.choices) ? json.choices[0] : null;",
  "  if (choice?.message?.content && typeof choice.message.content === 'string') {",
  "    return choice.message.content;",
  "  }",
  "  for (const key of ['text', 'message']) {",
  "    if (typeof json[key] === 'string') return json[key];",
  "  }",
  "  return JSON.stringify(json);",
  "}",
  "return extractOpenAIText(input);",
].join("\n");
