#!/usr/bin/env python3
"""Generate n8n Marketing Pipeline main workflow export JSON."""

from __future__ import annotations

import json
import uuid
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_PATH = REPO_ROOT / "n8n" / "workflows" / "marketing-pipeline-main.json"
FIELD_MAPPING_PATH = REPO_ROOT / "clickup" / "field-mapping.json"


def _id() -> str:
    return str(uuid.uuid4())


def _load_field_mapping() -> dict:
    return json.loads(FIELD_MAPPING_PATH.read_text(encoding="utf-8"))


def _extract_task_fields_js(field_mapping: dict) -> str:
    criterios_id = field_mapping["custom_fields"]["criterios_de_aceite"]["clickup_field_id"]
    agent_id = field_mapping["custom_fields"]["agent_id"]["clickup_field_id"]
    default_agent = field_mapping["custom_fields"]["agent_id"].get("default", "linkedin-writer")
    return f"""
const FIELD_IDS = {{
  criterios_de_aceite: {json.dumps(criterios_id)},
  agent_id: {json.dumps(agent_id)},
  default_agent_id: {json.dumps(default_agent)},
}};

function readCustomField(task, fieldId) {{
  if (!fieldId || fieldId === '<TBD>') return '';
  const fields = task.custom_fields || [];
  const match = fields.find((field) => String(field.id) === String(fieldId));
  if (!match || match.value === null || match.value === undefined) return '';
  if (typeof match.value === 'object') {{
    return String(match.value.value ?? match.value.name ?? match.value.label ?? '');
  }}
  return String(match.value);
}}

const task = $input.first().json;
const webhook = $('Extract Webhook Context').first().json;
const agentId = readCustomField(task, FIELD_IDS.agent_id).trim() || FIELD_IDS.default_agent_id;

return [{{
  json: {{
    task_id: String(task.id ?? webhook.task_id ?? ''),
    agent_id: agentId,
    task_title: String(task.name ?? ''),
    task_description: String(task.description ?? task.text_content ?? ''),
    criterios_de_aceite: readCustomField(task, FIELD_IDS.criterios_de_aceite),
    model: 'gemini-2.5-flash',
  }},
}}];
""".strip()


def _format_comment_js() -> str:
    return """
const agentOutput = $('Execute Call Agent').first().json;
const taskFields = $('Extract Task Fields').first().json;
const agentId = taskFields.agent_id ?? 'linkedin-writer';
const model = taskFields.model ?? 'gemini-2.5-flash';

const commentText = [
  '## LinkedIn Draft',
  '',
  agentOutput.deliverable_markdown ?? '',
  '',
  '---',
  '',
  '## Resumo',
  '',
  agentOutput.resumo ?? '',
  '',
  '---',
  '',
  '## Autochecagem',
  '',
  agentOutput.autochecagem ?? '',
  '',
  '---',
  `_Generated by ${agentId} (${model})_`,
].join('\\n');

return [{
  json: {
    task_id: taskFields.task_id,
    agent_id: agentId,
    model,
    comment_text: commentText,
    deliverable_markdown: agentOutput.deliverable_markdown,
    resumo: agentOutput.resumo,
    autochecagem: agentOutput.autochecagem,
  },
}];
""".strip()


def _agent_failure_js() -> str:
    return """
const output = $input.first().json;
const taskFields = $('Extract Task Fields').first().json;
console.log(JSON.stringify({
  task_id: taskFields.task_id,
  agent_id: taskFields.agent_id,
  execution_id: $execution.id,
  parse_success: false,
  error: output.error ?? 'Agent returned error envelope',
}));
throw new Error(`Call Agent failed: ${output.error ?? 'unknown error'}`);
""".strip()


def build_workflow() -> dict:
    field_mapping = _load_field_mapping()
    status_in_progress = field_mapping["statuses"]["in_progress"]
    status_review = field_mapping["statuses"]["review"]

    nodes = [
        {
            "parameters": {
                "httpMethod": "POST",
                "path": "marketing-pipeline-ready-to-work",
                "responseMode": "onReceived",
                "options": {},
            },
            "id": _id(),
            "name": "ClickUp Webhook",
            "type": "n8n-nodes-base.webhook",
            "typeVersion": 2,
            "position": [0, 300],
            "webhookId": _id(),
        },
        {
            "parameters": {
                "conditions": {
                    "options": {
                        "version": 2,
                        "leftValue": "",
                        "caseSensitive": True,
                        "typeValidation": "strict",
                    },
                    "combinator": "and",
                    "conditions": [
                        {
                            "id": _id(),
                            "leftValue": "={{ $json.history_items[0].field }}",
                            "rightValue": "status",
                            "operator": {"type": "string", "operation": "equals"},
                        },
                        {
                            "id": _id(),
                            "leftValue": "={{ $json.history_items[0].after.status }}",
                            "rightValue": "Ready to Work",
                            "operator": {"type": "string", "operation": "equals"},
                        },
                    ],
                },
                "options": {},
            },
            "id": _id(),
            "name": "Ready to Work?",
            "type": "n8n-nodes-base.if",
            "typeVersion": 2.2,
            "position": [240, 300],
        },
        {
            "parameters": {
                "jsCode": """
const payload = $input.first().json;
const items = payload.history_items || [];
const first = items[0] || {};
return [{
  json: {
    task_id: String(payload.task_id ?? ''),
    webhook_id: String(payload.webhook_id ?? ''),
    history_item_id: String(first.id ?? ''),
    list_id: String(first.parent_id ?? ''),
    received_at_ms: Date.now(),
  },
}];
""".strip(),
            },
            "id": _id(),
            "name": "Extract Webhook Context",
            "type": "n8n-nodes-base.code",
            "typeVersion": 2,
            "position": [480, 300],
        },
        {
            "parameters": {
                "operation": "get",
                "id": "={{ $json.task_id }}",
            },
            "id": _id(),
            "name": "GET ClickUp Task",
            "type": "n8n-nodes-base.clickUp",
            "typeVersion": 1,
            "position": [720, 300],
            "credentials": {
                "clickUpApi": {
                    "id": "CLICKUP_CREDENTIAL_ID",
                    "name": "ClickUp Marketing Pipeline",
                }
            },
        },
        {
            "parameters": {"jsCode": _extract_task_fields_js(field_mapping)},
            "id": _id(),
            "name": "Extract Task Fields",
            "type": "n8n-nodes-base.code",
            "typeVersion": 2,
            "position": [960, 300],
        },
        {
            "parameters": {
                "operation": "update",
                "id": "={{ $json.task_id }}",
                "updateFields": {
                    "status": status_in_progress,
                },
            },
            "id": _id(),
            "name": "Status → In Progress",
            "type": "n8n-nodes-base.clickUp",
            "typeVersion": 1,
            "position": [1200, 300],
            "credentials": {
                "clickUpApi": {
                    "id": "CLICKUP_CREDENTIAL_ID",
                    "name": "ClickUp Marketing Pipeline",
                }
            },
        },
        {
            "parameters": {
                "jsCode": """
const fields = $('Extract Task Fields').first().json;
return [{
  json: {
    agent_id: fields.agent_id,
    task_title: fields.task_title,
    task_description: fields.task_description,
    criterios_de_aceite: fields.criterios_de_aceite,
    task_id: fields.task_id,
  },
}];
""".strip(),
            },
            "id": _id(),
            "name": "Prepare Call Agent Input",
            "type": "n8n-nodes-base.code",
            "typeVersion": 2,
            "position": [1320, 300],
        },
        {
            "parameters": {
                "source": "database",
                "workflowId": {
                    "__rl": True,
                    "mode": "id",
                    "value": "CALL_AGENT_WORKFLOW_ID",
                },
                "mode": "once",
                "options": {},
            },
            "id": _id(),
            "name": "Execute Call Agent",
            "type": "n8n-nodes-base.executeWorkflow",
            "typeVersion": 1.2,
            "position": [1560, 300],
        },
        {
            "parameters": {
                "conditions": {
                    "options": {
                        "version": 2,
                        "leftValue": "",
                        "caseSensitive": True,
                        "typeValidation": "strict",
                    },
                    "combinator": "and",
                    "conditions": [
                        {
                            "id": _id(),
                            "leftValue": "={{ $json.error }}",
                            "rightValue": "",
                            "operator": {"type": "string", "operation": "notExists"},
                        }
                    ],
                },
                "options": {},
            },
            "id": _id(),
            "name": "Agent Output OK?",
            "type": "n8n-nodes-base.if",
            "typeVersion": 2.2,
            "position": [1800, 300],
        },
        {
            "parameters": {"jsCode": _format_comment_js()},
            "id": _id(),
            "name": "Format Draft Comment",
            "type": "n8n-nodes-base.code",
            "typeVersion": 2,
            "position": [2040, 220],
        },
        {
            "parameters": {
                "resource": "comment",
                "operation": "create",
                "id": "={{ $json.task_id }}",
                "commentText": "={{ $json.comment_text }}",
            },
            "id": _id(),
            "name": "POST Task Comment",
            "type": "n8n-nodes-base.clickUp",
            "typeVersion": 1,
            "position": [2280, 220],
            "credentials": {
                "clickUpApi": {
                    "id": "CLICKUP_CREDENTIAL_ID",
                    "name": "ClickUp Marketing Pipeline",
                }
            },
        },
        {
            "parameters": {
                "operation": "update",
                "id": "={{ $('Extract Task Fields').item.json.task_id }}",
                "updateFields": {
                    "status": status_review,
                },
            },
            "id": _id(),
            "name": "Status → Review",
            "type": "n8n-nodes-base.clickUp",
            "typeVersion": 1,
            "position": [2520, 220],
            "credentials": {
                "clickUpApi": {
                    "id": "CLICKUP_CREDENTIAL_ID",
                    "name": "ClickUp Marketing Pipeline",
                }
            },
        },
        {
            "parameters": {"jsCode": _agent_failure_js()},
            "id": _id(),
            "name": "Agent Parse Failure",
            "type": "n8n-nodes-base.code",
            "typeVersion": 2,
            "position": [2040, 420],
        },
        {
            "parameters": {},
            "id": _id(),
            "name": "Ignore Non-Matching Webhook",
            "type": "n8n-nodes-base.noOp",
            "typeVersion": 1,
            "position": [480, 500],
        },
    ]

    connections = {
        "ClickUp Webhook": {
            "main": [[{"node": "Ready to Work?", "type": "main", "index": 0}]]
        },
        "Ready to Work?": {
            "main": [
                [{"node": "Extract Webhook Context", "type": "main", "index": 0}],
                [{"node": "Ignore Non-Matching Webhook", "type": "main", "index": 0}],
            ]
        },
        "Extract Webhook Context": {
            "main": [[{"node": "GET ClickUp Task", "type": "main", "index": 0}]]
        },
        "GET ClickUp Task": {
            "main": [[{"node": "Extract Task Fields", "type": "main", "index": 0}]]
        },
        "Extract Task Fields": {
            "main": [[{"node": "Status → In Progress", "type": "main", "index": 0}]]
        },
        "Status → In Progress": {
            "main": [[{"node": "Prepare Call Agent Input", "type": "main", "index": 0}]]
        },
        "Prepare Call Agent Input": {
            "main": [[{"node": "Execute Call Agent", "type": "main", "index": 0}]]
        },
        "Execute Call Agent": {
            "main": [[{"node": "Agent Output OK?", "type": "main", "index": 0}]]
        },
        "Agent Output OK?": {
            "main": [
                [{"node": "Format Draft Comment", "type": "main", "index": 0}],
                [{"node": "Agent Parse Failure", "type": "main", "index": 0}],
            ]
        },
        "Format Draft Comment": {
            "main": [[{"node": "POST Task Comment", "type": "main", "index": 0}]]
        },
        "POST Task Comment": {
            "main": [[{"node": "Status → Review", "type": "main", "index": 0}]]
        },
    }

    return {
        "name": "Marketing Pipeline",
        "nodes": nodes,
        "connections": connections,
        "active": False,
        "settings": {"executionOrder": "v1"},
        "versionId": _id(),
        "meta": {
            "templateCredsSetupCompleted": False,
            "instanceId": "agentic-mkt-marketing-pipeline-export",
        },
        "tags": [{"name": "marketing-pipeline"}],
    }


def main() -> None:
    workflow = build_workflow()
    OUTPUT_PATH.write_text(json.dumps(workflow, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
